[build]
  base = "/"
  publish = "public/"
  command = "yarn build"
  environment = { YARN_VERSION = "1.22.10" }
  
[[redirects]]
  from = "/is"
  to = "/images/code4rena_is.pdf"
  status = 200  

[context.deploy-preview]
  ignore = "bash ./netlify-ignore-branch.sh"
  environment = { STAGING = "true" }

[context.staging]
  environment = { STAGING = "true" }

[functions]
  directory = "functions/"
  included_files = ["_data/contests/*", "_data/handles/*.json"]
